export default [
  {
    id: 1,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status:true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 2,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: false,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 3,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 4,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 5,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 6,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 7,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 8,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 9,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 10,
    company: 'Doanh nghiệp A',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
  {
    id: 11,
    company: 'Doanh nghiệp C',
    customer_group: 'Nhóm con test',
    customer_group_root: 'Nhóm test',
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
  },
]
