export default [
  {
    id: 1,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '096999999',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Sinh',
    },
    country: 'VN',
    status: true,
    act: '',
  },
  {
    id: 2,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '096999999',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Sinh',
    },
    country: 'VN',
    status: true,
    act: '',
  },
  {
    id: 3,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '096999999',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Sinh',
    },
    country: 'VN',
    status: true,
    act: '',
  },
  {
    id: 4,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '096999999',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Sinh',
    },
    country: 'VN',
    status: true,
    act: '',
  },
  {
    id: 5,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '096999999',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Sinh',
    },
    country: 'VN',
    status: true,
    act: '',
  },
  {
    id: 6,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '096999999',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Sinh',
    },
    country: 'VN',
    status: true,
    act: '',
  },
  {
    id: 7,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '096999999',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Sinh',
    },
    country: 'VN',
    status: true,
    act: '',
  },
  {
    id: 8,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '096999999',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Sinh',
    },
    country: 'VN',
    status: true,
    act: '',
  },
  {
    id: 9,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-04-2022',
    },
    company: 'DDDD Company',
    order_source: 0,
    customer: 'Danh Sinh',
    phone_number: '0982222214',
    creater: {
      id: 1,
      role: 'Admin',
      name: 'Danh Quốc dũng',
    },
    country: 'THA',
    status: false,
    act: '',
  },
]
