export default [
  {
    id: 1,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 2,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 3,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 4,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 5,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 6,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 7,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 8,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 9,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 10,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 11,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 12,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
  {
    id: 13,
    company: 'Sinh',
    order_status_name: 'Hủy lớp',
    color: 'red',
    level: 4,
    location: 1,
    status: true,
    date: {
      created_at: '20-03-2022',
      updated_at: '20-05-2022',
    },
  },
]
